[package]
<<<<<<< HEAD
name = "esp-hal-mfrc522"
version = "0.1.0"
=======
name = "mfrc522-esp-hal"
version = "0.1.1"
>>>>>>> 7e82223 (chore: version bump (also for esp-hal in example))
authors = ["filipton <filipton12@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Simple mfrc522 library for esp-hal (can be used on any hal that implements embedded-hal-async)"

[lib]

[dependencies]
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
heapless = "0.8.0"
log = { version = "0.4.22" }
<<<<<<< HEAD
embassy-time = { version = "0.3.1", optional = true }
=======
embassy-time = { version = "0.3.2", optional = true }
>>>>>>> 7e82223 (chore: version bump (also for esp-hal in example))

[features]
default = []
embassy-time = ["dep:embassy-time"]
