[package]
name = "mfrc522-esp-hal"
version = "0.1.0"
authors = ["filipton <filipton12@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]

[dependencies]
embassy-time = "0.3.1"
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
heapless = "0.8.0"
log = { version = "0.4.21" }
