[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
# embassy-embedded-hal = "0.1.0"
# embedded-hal = "1.0.0"
# embedded-hal-async = "1.0.0"
embassy-executor = { version = "0.5.0", features = ["arch-riscv32"] }
embassy-time = "0.3.1"
esp-backtrace = { version = "0.12.0", features = [
    "esp32s3",
    "exception-handler",
    "panic-handler",
    "println",
] }
esp-hal = { version = "0.18.0", features = [ "esp32s3", "async", "embedded-hal" ] }
esp-hal-embassy = { version = "0.1.0", features = ["esp32s3", "time-timg0", "integrated-timers"] }
esp-println = { version = "0.9.1", features = ["esp32s3", "log"] }
heapless = "0.8.0"
log = { version = "0.4.21" }
static_cell = { version = "2.1.0", features = ["nightly"] }

mfrc522-esp-hal = { path = "../" }
[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1 # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false
